language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm i

script:
  - npm run build


#命令里面的变量都是在Travis CI里配置过的。 cd ./shopCar 找到dist移动到 travi
after_script:
  - git clone https://github.com/zouyu01-sz/travi.git
  - ls
  - cd ./dist
  - git init
  - git config user.name "zouyu01-sz"
  - git config user.email "316675462@qq.com"
  - git add .
  - git commit -m "Update tools"
  - git push -f git@github.com:https://github.com/zouyu01-sz/travi.git master:gh-pages


# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master